title:        RSS Aggregator
url:          http://audreywatters.github.io/rss-aggregator/

version:      1.1.1
author:
  name:       'Audrey Watters'
  email:      'mail@audreywatters.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 250
paginate_path: "/updates/page:num"

categories_path : /categories.html
tags_path : /tags.html
